### ISSUE TITLE
Save with original file extension, without browser type detection

### ISSUE THREAD

**Issue by u5r0** [NyllRE/nuxt-file-storage#12]
When un[common mime types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) are uploaded, they're saved as `application/octet-stream`, and even corner cases like [this](https://github.com/mdn/content/issues/13409). Detecting types with original ext as in the `name` property would fix this

Thanks

**Comment by NyllRE** [comment]
would you give me examples of uncommon file types that you tested so I can test with them?

**Comment by u5r0** [comment]
`.kml`, `.kmz`, `.dwg` 
and `.zip` as mentioned in the above issue is detected as `application/x-zip-compressed` not as `application/zip`

**Comment by NyllRE** [comment]
Hey @u5r0, I have fixed the issue with the new [release v0.2.6](https://github.com/NyllRE/nuxt-file-storage/releases/tag/v0.2.6). check if everything is working as expected and tell me if there's any issues!
