### ISSUE TITLE
Cannot detect handleFileInput complete

### ISSUE THREAD

**Issue by siaikin** [NyllRE/nuxt-file-storage#13]
When I upload multiple files, I need to wait for the serialization to complete before calling the upload interface. But I have no way of knowing if handleFileInput completes.

Maybe handleFileInput could return a Promise?

**Comment by NyllRE** [comment]
sounds like a good addition, will work on it for the next version

**Comment by NyllRE** [comment]
@siaikin update the module to `0.2.7` to use this feature, tell me if it fits your usecase so I can close this comment. Hope this helps!
