### ISSUE TITLE
configure absolute path to deploy Vercel service.

### ISSUE THREAD

**Issue by lusacramento** [NyllRE/nuxt-file-storage#14]
I want to deploy an app built in Nuxt3 and I use nuxt-file-storage for upload images. How to configure the "mount" var once that I do not have access the Vercel absolute path? This is first time I use nuxt-file-storage and Vercel too.

**Comment by NyllRE** [comment]
did you use environment variables to specify the absolute path in vercel? either that or I'm not understanding what you mean by not having access to the path

**Comment by NyllRE** [comment]
I believe I understood the issue from #16 and I think it's doable from https://vercel.com/docs/build-output-api/v3/primitives

check it and let me know if it worked

**Comment by avoytulevich** [comment]
Hi.how to create a folder for storage outside my project
I use .env as
FILE_STORAGE=‘/var/www/MyFileStorage’
but this folder is created inside the project

**Comment by NyllRE** [comment]
@avoytulevich are you sure you are using the correct absolute path? for reference in Linux you should start with `/home/nyll/my_projects/...` and on windows it's more like `C:/documents/my_projects/... ` check your correct config

**Comment by NyllRE** [comment]
@lusacramento I will close this issue for now. Please feel free to request for it to be re-opened when you can provide me with more details around your issue. It's worth noting that I am planning to add more documentation around making the project ready for production.
