### ISSUE TITLE
Image source not readable

### ISSUE THREAD

**Issue by HaciAli-MIZRAK** [NyllRE/nuxt-file-storage#15]
Hello, I am trying to use your package but Laravel gives this warning "Image source not readable". When I test it with Postman, the installation is successful. Where could be the problem?

**Comment by NyllRE** [comment]
hello, i sort of need more information as I am not experienced with laravel but it sounds like an issue on laravel's side.
Is there maybe any logs or perhaps specific situations that this issue occurs in?

**Comment by NyllRE** [comment]
@HaciAli-MIZRAK I will close this issue due to lack of information around your issue. Feel free to request for it to be open whenever you can provide more information around your issue!
