### ISSUE TITLE
Handle multiple file inputs in one form

### ISSUE THREAD

**Issue by idmedia-fritscher** [NyllRE/nuxt-file-storage#18]
Hi,
I tried to build a form which includes multiple file input fields. I attached `handleFileInput` to each field, kinda expecting it to put the files onto the `files` array but instead the files are overwritten, so only the last file input in the form is actually considered. Am I missing something here or is it a feature that just doesn't exist?
Thanks!

**Comment by NyllRE** [comment]
yes this happens because everytime you call `useFileStorage()` composable it renders a handler and a storage, to do what you're trying to do you should scope each call, try this and let me know if it works:

```ts
const { handleFileInput: firstInputHandler, files: firstFiles } = useFileStorage() 
```

and repeat for each input renaming them to `secondInputHandler` or whichever you prefer. this way you have a handler and an object for each input

**Comment by idmedia-fritscher** [comment]
Thanks @NyllRE,
actually I only call `useFilestorage()` once:
```
<script setup>
    const { files, handleFileInput } = useFileStorage();
    const submit = () => {
        console.log(files.value)
    }
    const fields = [my, array, of, field, definitions]
</script>
<template>
    <form @submit="submit">
        <CustomInputField v-for="field in fields" :fileHandler="handleFileInput" />
    </form>
</template>
```

**Comment by NyllRE** [comment]
so does this solution work?

**Comment by idmedia-fritscher** [comment]
No, since you reset the files array on every `handleFileInput()` call. Why exactly is this done?

**Comment by NyllRE** [comment]
as I said, each call for the `useFileStorage()` has the fileInputHandler linked to the files object. try the solution I gave you where you call `useFileStorage()` for each file input and provide a unique file input handler for each one.

**Comment by NyllRE** [comment]
@idmedia-fritscher Hello, I need to know if you tried the solution I suggested and if it worked or I will have to close the issue

**Comment by NyllRE** [comment]
Issue closed for inactivity
