### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by pi0** [NyllRE/nuxt-file-storage#2]
Context: https://github.com/nuxt/modules/pull/934

---

Only i am concerned we might try to find a less confusing name both for package and exposed comosable. Nuxt module naming is `nuxt-{name}`. The extra nitro prefix is little confusing. 

Also for composable naming exposed by modules, we usually advice to use clear prefixes. `useNuxt*`/`useNitro*` are usually used for framework composables.

Therefore I suggest:

- Rename package to something like `nuxt-file-storage`
- Rename composable to something like `useFileStorage()`

**Comment by NyllRE** [comment]
@pi0 I have deprecated the old [nuxt-nitro-storage](https://www.npmjs.com/package/nuxt-nitro-storage) module and successfuly renamed the composable and the package to [nuxt-file-storage](https://www.npmjs.com/package/nuxt-file-storage). I hope everything is perfect for releasing to the modules repository!
