### ISSUE TITLE
How to make a multiload

### ISSUE THREAD

**Issue by pir0zh0k** [NyllRE/nuxt-file-storage#21]
I have a need to do a sequential download of several files. Is there a possibility to implement such a thing?
So that the files are not replaced, but added one by one to the array.

**Comment by NyllRE** [comment]
I will implement a fix for it to not delete them one by one but in the mean time I suggest you take the `useFileStorage.ts` composables file and put it in your project and in the `handleFileInput` composable remove the first line `files.value.splice(0)`

**Comment by pir0zh0k** [comment]
> I will implement a fix for it to not delete them one by one but in the mean time I suggest you take the `useFileStorage.ts` composables file and put it in your project and in the `handleFileInput` composable remove the first line `files.value.splice(0)`

Thank's, bro

**Comment by NyllRE** [comment]
issue is fixed with [v0.2.9](https://github.com/NyllRE/nuxt-file-storage/releases/tag/v0.2.9).

Thanks for reporting the issue!
