### ISSUE TITLE
Types not exported

### ISSUE THREAD

**Issue by Korny666** [NyllRE/nuxt-file-storage#23]
For a better comfort when developing i want to use the here defined types. 
https://github.com/NyllRE/nuxt-file-storage/blob/master/types/types.d.ts

Suggestion is here
https://github.com/NyllRE/nuxt-file-storage/pull/26

**Comment by NyllRE** [comment]
issue fixed with [v0.2.9](https://github.com/NyllRE/nuxt-file-storage/releases/tag/v0.2.9)
