### ISSUE TITLE
Options API

### ISSUE THREAD

**Issue by avpuchkova** [NyllRE/nuxt-file-storage#27]
Hello! Could you give an example of how the module can be used with the Options API?

**Comment by NyllRE** [comment]
the library is currently made with composables, which is why you'd correctly guess it uses the composition api. if you need to use it in your options api then you should call the setup function:

```html
<script>
export default {
    setup() {
        const { fileInputHandler } = useFileStorage()
    }
</script>
```

test this and tell me how it goes

**Comment by NyllRE** [comment]
For more info around the usage of composables in options api please refer to the [Vue Docs](https://vuejs.org/guide/reusability/composables.html#using-composables-in-options-api)
